version: '3'
volumes:
  grm-app:
#    name: grm-app
    driver: local
services:
  php:
    container_name: grm-php7-fpm
    image: 8122227024/swarm-app
    volumes:
    - grm-app:/grm
    depends_on:
    - mysql
    networks:
    - app-net
  web:
    container_name: grm-nginx
    image: nginx:latest
    ports:
    - 8080:80
    volumes:
    - ./app/nginx/conf.d:/etc/nginx/conf.d
    - grm-app:/grm
    depends_on:
    - php
    networks:
    - app-net
  mysql:
    image: mysql:5.7
    container_name: grm-mysql
    ports:
    - 6601:3306
    volumes:
    - ./app/mysql/mysql.conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: infi
    networks:
    - app-net
networks:
  app-net:
    driver: overlay
